In [1]:
import pandas_datareader as web

In [2]:
import datetime

In [4]:
start = datetime.datetime(2015,1,1)
end = datetime.datetime(2017,1,1)

In [7]:
facebook = web.DataReader('FB','google',start,end)

In [8]:
facebook

              Open    High     Low   Close    Volume
Date
2016-09-22  130.50  130.73  129.56  130.08  15538307
2016-09-23  127.56  128.60  127.30  127.96  28326266
2016-09-26  127.37  128.16  126.80  127.31  15064940
2016-09-27  127.61  129.01  127.43  128.69  15637111
2016-09-28  129.21  129.47  128.40  129.23  12047636
2016-09-29  129.18  129.29  127.55  128.09  14532241
2016-09-30  128.03  128.59  127.45  128.27  18402945
2016-10-03  128.38  129.09  127.80  128.77  13156943
2016-10-04  129.17  129.28  127.55  128.19  14307548
2016-10-05  128.25  128.80  127.83  128.47  12386753
2016-10-06  128.43  129.06  128.08  128.74  11682729
2016-10-07  129.04  129.25  128.33  128.99  12804420
2016-10-10  129.68  130.70  129.20  130.24  15138720
2016-10-11  130.23  130.64  128.23  128.88  17537928
2016-10-12  129.01  129.66  128.46  129.05  11072991
2016-10-13  128.21  128.25  126.75  127.82  17139306
2016-10-14  128.49  128.95  127.58  127.88  13345292
2016-10-17  128.20  128.47  127.32  127.54  11351681
2016-10-18  128.68  129.39  128.01  128.57  13503967
2016-10-19  128.74  130.47  128.60  130.11  16752321
2016-10-20  130.07  130.66  129.50  130.00  13167503
2016-10-21  129.78  132.13  129.70  132.07  19088794
2016-10-24  132.72  133.40  132.15  133.28  17470227
2016-10-25  133.50  133.50  132.22  132.29  13336787
2016-10-26  131.64  132.26  130.94  131.04  13084731
2016-10-27  131.74  131.80  129.27  129.69  16741393
2016-10-28  130.50  132.97  129.93  131.29  24545547
2016-10-31  132.01  132.12  130.88  130.99  15668982
2016-11-01  131.41  131.94  128.65  129.50  22077779
2016-11-02  130.23  130.23  126.28  127.17  50190225
...            ...     ...     ...     ...       ...
2017-08-08  171.88  173.05  170.62  171.23  14393524
2017-08-09  169.98  171.45  169.56  171.18  10814984
2017-08-10  170.06  170.59  166.85  167.40  20832746
2017-08-11  167.95  168.82  166.85  168.08  13791153
2017-08-14  170.09  171.08  169.29  170.75  12954231
2017-08-15  171.49  171.50  170.01  171.00   8729172
2017-08-16  171.25  171.38  169.24  170.00  15779924
2017-08-17  169.34  169.86  166.85  166.91  17216030
2017-08-18  166.84  168.67  166.21  167.41  15093638
2017-08-21  167.16  168.00  165.82  167.78  11907488
2017-08-22  168.28  169.87  167.15  169.64  11390975
2017-08-23  168.84  169.36  168.20  168.71   9856473
2017-08-24  168.88  169.29  166.41  167.74  14030420
2017-08-25  167.86  168.38  166.18  166.32  12614477
2017-08-28  166.91  167.70  166.33  167.24   8553741
2017-08-29  165.25  168.42  165.00  168.05  11120986
2017-08-30  168.17  170.18  167.63  169.92  11138293
2017-08-31  170.40  172.14  170.06  171.97  17226465
2017-09-01  172.40  172.92  171.31  172.02  11677589
2017-09-05  171.27  172.39  169.55  170.72  13221127
2017-09-06  170.91  172.48  169.57  172.09  13906342
2017-09-07  171.94  173.31  170.27  173.21  18049527
2017-09-08  173.09  173.49  170.80  170.95  10998459
2017-09-11  172.40  173.89  172.20  173.51  12372040
2017-09-12  173.76  174.00  171.75  172.96  11186328
2017-09-13  173.01  173.17  172.06  173.05   9119295
2017-09-14  172.26  172.28  170.50  170.96  15615654
2017-09-15  170.88  172.34  170.26  171.64  15660539
2017-09-18  171.99  172.07  169.34  170.01  12954013
2017-09-19  170.62  172.56  170.36  172.52  13168595

[250 rows x 5 columns]

In [9]:
from pandas_datareader import Options
fb_options = Options('FB','google')

In [11]:
options_df = fb_options.get_options_data(expiry=fb_options.expiry_dates[0])